server:
  port: 8081
spring:
  application:
    name: hmdp
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://218.194.61.54:9875/hmdp?useSSL=false&serverTimezone=UTC
    username: hmdp_user
    password: password
  redis:
    host: 218.194.61.54
    port: 9872
    password: password
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
  jackson:
    default-property-inclusion: non_null # JSON处理时忽略非空字段
mybatis-plus:
  type-aliases-package: com.gxz.entity # 别名扫描包
logging:
  level:
    com.gxz: debug