spring:
  redis:
    host: 218.194.61.139
    port: 9872
    password: password
    lettuce: #基于lettuce（类似jedis的java客户端）创建连接池
      pool:
        max-active: 8 #最大连接数
        max-idle: 4 #最大空闲连接
        min-idle: 0 #最小空闲连接
        max-wait: 1000 #池满等待时间